apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: CONCEPTNET_BUILD_DATA
          value: /data/conceptnet
        - name: CONCEPTNET_DATA
          value: /data/conceptnet
        - name: CONCEPTNET_DB_HOSTNAME
          value: db
        - name: CONCEPTNET_RATE_LIMITING
          value: "0"
        image: rspeer/conceptnet:5.5.5
        name: api
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /data/conceptnet
          name: data
        - mountPath: /data/nginx
          name: cache
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: cache
        persistentVolumeClaim:
          claimName: cache
status: {}
