apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: conceptnet5
        image: rspeer/conceptnet-data:5.5.5
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /data/conceptnet
          name: data
        - mountPath: /var/lib/postgresql/data
          name: psql
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: psql
        persistentVolumeClaim:
          claimName: psql
status: {}
